const fs = require('fs');
const path = 'c:/Users/yepur/Desktop/My_Projects/Ghost_Writer/src/components/Launcher.tsx';
const content = fs.readFileSync(path, 'utf8');
const lines = content.split(/\r?\n/);

// We know the broken part is around 666 to 810
const head = lines.slice(0, 665);
const tail = lines.slice(810);

const middle = [
'                                         {/* Iterating Date Groups */}',
'                                         {sortedGroups.map((label) => (',
'                                             <section key={label}>',
'                                                 <h3 className="text-[13px] font-medium text-text-secondary mb-3 pl-1">{label}</h3>',
'                                                 <div className="space-y-1">',
'                                                     {groupedMeetings[label].map((m) => {',
'                                                         let isMeeting = true;',
'                                                         try {',
'                                                             if (m.context_json) {',
'                                                                 const ctx = JSON.parse(m.context_json);',
'                                                                 isMeeting = !!ctx.isMeetingMode;',
'                                                             }',
'                                                         } catch (e) {}',
'',
'                                                         return (',
'                                                             <motion.div',
'                                                                 key={m.id}',
'                                                                 layoutId={`meeting-${m.id}`}',
'                                                                 className="group relative flex items-center justify-between px-5 py-3.5 rounded-2xl bg-[var(--bg-card-alpha)] hover:bg-bg-item-surface transition-all cursor-pointer border border-border-subtle hover:border-border-muted"',
'                                                                 onClick={() => handleOpenMeeting(m)}',
'                                                             >',
'                                                                 <div className="flex flex-col gap-0.5 max-w-[65%]">',
'                                                                     <div className="flex items-center gap-2">',
'                                                                         <div className={`font-semibold text-[14px] truncate ${m.title === \'Processing...\' ? \'text-accent-primary italic animate-pulse\' : \'text-text-primary\'}`}>',
'                                                                             {m.title}',
'                                                                         </div>',
'                                                                         {activeTab === \'all\' && (',
'                                                                             <div className={`shrink-0 p-1 rounded-md ${isMeeting ? \'bg-blue-400/10 text-blue-400\' : \'bg-emerald-400/10 text-emerald-400\'}`} title={isMeeting ? \'Meeting\' : \'Interview\'}>',
'                                                                                 {isMeeting ? <Users size={10} /> : <User size={10} />}',
'                                                                             </div>',
'                                                                         )}',
'                                                                     </div>',
'                                                                     {m.summary && (',
'                                                                         <div className="text-[11px] text-text-tertiary truncate opacity-60">',
'                                                                             {m.summary}',
'                                                                         </div>',
'                                                                     )}',
'                                                                 </div>',
'',
'                                                                 {/* Time & Duration Section */}',
'                                                                 <div className="flex items-center gap-5">',
'                                                                     {m.title === \'Processing...\' ? (',
'                                                                         <div className="flex items-center gap-2 transition-all duration-200 ease-out group-hover:opacity-0 group-hover:translate-x-2">',
'                                                                             <RefreshCw size={12} className="animate-spin text-accent-primary" />',
'                                                                             <span className="text-[10px] text-accent-primary font-bold uppercase tracking-wider">Processing</span>',
'                                                                         </div>',
'                                                                     ) : (',
'                                                                         <div className="flex flex-col items-end gap-1.5 transition-all duration-200 ease-out group-hover:opacity-0 group-hover:translate-x-2">',
'                                                                             <span className="text-[11px] text-text-secondary font-medium uppercase tracking-tight">',
'                                                                                 {formatTime(m.date)}',
'                                                                             </span>',
'                                                                             <span className="bg-bg-item-surface text-text-tertiary text-[9px] px-2 py-0.5 rounded-full font-bold tracking-widest border border-border-subtle">',
'                                                                                 {formatDurationPill(m.duration)}',
'                                                                             </span>',
'                                                                         </div>',
'                                                                     )}',
'                                                                 </div>',
'',
'                                                                 {/* Context Menu Trigger */}',
'                                                                 <div className="absolute right-3 top-1/2 -translate-y-1/2 opacity-0 translate-x-4 transition-all duration-300 ease-out group-hover:opacity-100 group-hover:translate-x-0">',
'                                                                     <button',
'                                                                         className="p-1.5 text-text-secondary hover:text-text-primary transition-colors"',
'                                                                         onClick={(e) => {',
'                                                                             e.stopPropagation();',
'                                                                             setActiveMenuId(activeMenuId === m.id ? null : m.id);',
'                                                                         }}',
'                                                                     >',
'                                                                         <MoreHorizontal size={16} />',
'                                                                     </button>',
'                                                                 </div>',
'',
'                                                                 {/* Dropdown Menu */}',
'                                                                 <AnimatePresence>',
'                                                                     {activeMenuId === m.id && (',
'                                                                         <motion.div',
'                                                                             initial={{ opacity: 0, scale: 0.95, y: 10 }}',
'                                                                             animate={{ opacity: 1, scale: 1, y: 0 }}',
'                                                                             exit={{ opacity: 0, scale: 0.95, y: 5 }}',
'                                                                             transition={{ duration: 0.1 }}',
'                                                                             className="absolute right-0 top-full mt-1 w-[90px] bg-[#1E1E1E]/80 backdrop-blur-xl border border-white/10 rounded-lg shadow-2xl z-50 overflow-hidden"',
'                                                                             onClick={(e) => e.stopPropagation()}',
'                                                                             onMouseEnter={() => setMenuEntered(true)}',
'                                                                             onMouseLeave={() => {',
'                                                                                 if (menuEntered) setActiveMenuId(null);',
'                                                                             }}',
'                                                                         >',
'                                                                             <div className="p-1 flex flex-col gap-0.5">',
'                                                                                 <button',
'                                                                                     className="w-full flex items-center gap-2 px-3 py-1.5 text-[12px] text-text-primary hover:bg-white/10 rounded-lg transition-colors text-left"',
'                                                                                     onClick={async () => {',
'                                                                                         setActiveMenuId(null);',
'                                                                                         analytics.trackPdfExported();',
'                                                                                         if (window.electronAPI && window.electronAPI.getMeetingDetails) {',
'                                                                                             try {',
'                                                                                                 const fullMeeting = await window.electronAPI.getMeetingDetails(m.id);',
'                                                                                                 if (fullMeeting) {',
'                                                                                                     generateMeetingPDF(fullMeeting);',
'                                                                                                 } else {',
'                                                                                                     generateMeetingPDF(m);',
'                                                                                                 }',
'                                                                                             } catch (e) {',
'                                                                                                 console.error("Failed to fetch details for PDF", e);',
'                                                                                                 generateMeetingPDF(m);',
'                                                                                             }',
'                                                                                         } else {',
'                                                                                             generateMeetingPDF(m);',
'                                                                                         }',
'                                                                                     }}',
'                                                                                 >',
'                                                                                     <Download size={13} />',
'                                                                                     Export',
'                                                                                 </button>',
'                                                                                 <button',
'                                                                                     className="w-full flex items-center gap-2 px-3 py-1.5 text-[12px] text-red-400 hover:bg-red-500/10 hover:text-red-300 rounded-lg transition-colors text-left"',
'                                                                                     onClick={async () => {',
'                                                                                         if (window.electronAPI && window.electronAPI.deleteMeeting) {',
'                                                                                             const success = await window.electronAPI.deleteMeeting(m.id);',
'                                                                                             if (success) {',
'                                                                                                 setMeetings(prev => prev.filter(meeting => meeting.id !== m.id));',
'                                                                                                 if (forwardMeeting && forwardMeeting.id === m.id) setForwardMeeting(null);',
'                                                                                             }',
'                                                                                         }',
'                                                                                         setActiveMenuId(null);',
'                                                                                     }}',
'                                                                                 >',
'                                                                                     <Trash2 size={13} />',
'                                                                                     Delete',
'                                                                                 </button>',
'                                                                             </div>',
'                                                                         </motion.div>',
'                                                                     )}',
'                                                                 </AnimatePresence>',
'                                                             </motion.div>',
'                                                         );',
'                                                     })}',
'                                                 </div>',
'                                             </section>',
'                                         ))}',
'                                     </motion.div>',
'                                 </AnimatePresence>'
];

const newContent = head.concat(middle).concat(tail).join('\n');
fs.writeFileSync(path, newContent);
console.log('Successfully patched Launcher.tsx');
